- hosts: localhost
  connection: local
  gather_facts: no
  vars:
    homebrew_taps:
      - caskroom/cask

    homebrew_packages:
      - name: awscli
      - name: direnv
      - name: jq
      - name: noti
      - name: packer
      - name: terraform
      - name: wget

      # for phpenv
      - name: autoconf
      - name: automake
      - name: bison
      - name: homebrew/versions/openssl101
      - name: libjpeg
      - name: libmcrypt
      - name: libpng
      - name: libxml2
      - name: re2c

    homebrew_cask_packages:
      - name: appcleaner
      - name: clipmenu
      - name: docker
      - name: dropbox
      - name: firefox
      - name: flash-player
      - name: google-chrome
      - name: google-japanese-ime
      - name: iterm2
      - name: sequel-pro
      - name: sketch
      - name: slack
      - name: sublime-text
      - name: teamviewer
      - name: transmit
      - name: vagrant
      - name: virtualbox

  handlers:

  tasks:
    # brew tap
    - name: install taps of homebrew
      homebrew_tap: tap="{{ item }}" state=present
      with_items: "{{ homebrew_taps }}"
      tags:
        - brew

    # brew update
    - name: update homebrew
      homebrew: update_homebrew=yes
      tags:
        - brew

    # brew instal
    - name: install homebrew packages
      homebrew: name="{{ item.name }}" state="{{ item.state|default('latest') }}" install_options="{{ item.install_options|default() }}"
      with_items: "{{ homebrew_packages }}"
      tags:
        - brew

    # brew cask install
    - name: install homebrew cask packages
      homebrew_cask: name="{{ item.name }}" state=present
      with_items: "{{ homebrew_cask_packages }}"
      tags:
        - cask
